apiVersion: v1
kind: ConfigMap
metadata:
  name: mongodb-python-config
data:
  dburl: mongodb-service
  mport: 27017
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-python
spec:
  selector:
    matchLabels:
      app: mongopy
  template:
    metadata:
      labels:
        app: mongopy
    spec:
      containers:
      - name: mongopy
        image: ikn1062/pymongo-kb
        resources:
          limits:
            memory: "128Mi"
            cpu: "250m"
        ports:
        - containerPort: 8081
        env:
        - name: MONGO_USERNAME
          valueFrom:
            configMapKeyRef:
              name: mongo-login
              key: mongo-root-username 
        - name: MONGO_PASS
          valueFrom:
            configMapKeyRef:
              name: mongo-login
              key: mongo-root-password  
        - name: MONGO_SERVER
          valueFrom:
            configMapKeyRef:
              name: mongodb-python-config
              key: dburl
        - name: MONGO_PORT
            valueFrom:
              configMapKeyRef:
                name: mongodb-python-config
                key: mport

