apiVersion: v1
kind: ConfigMap
metadata:
  name: server-config-file
data:
  server.ini: |
  [server_config]
  SERVER_PORT = 5050
  TIME_LOWER = 1
  TIME_UPPER = 3

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-deployment
spec:
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
      - name: server
        image: ikn1062/pyservice
        resources:
          limits:
            memory: "128Mi"
            cpu: "250m"
        volumeMounts:
        - name: server-config
          mountPath: app
      volumes:
        - name: server-config
          configMap:
            name: server-config-file
